included:
  - Sources
  - Tests
excluded:
  - .build
  - DerivedData

disabled_rules:
  - closure_body_length
  - closure_spacing
  - file_name
  - for_where
  - function_parameter_count
  - identifier_name
  - implicit_optional_initialization
  - large_tuple
  - missing_docs
  - nesting
  - non_optional_string_data_conversion
  - nslocalizedstring_require_bundle
  - opening_brace
  - superfluous_disable_command
  - trailing_comma
  - type_name
  - unused_import
  - unused_optional_binding
  - vertical_parameter_alignment
  - vertical_whitespace
  - xctfail_message

cyclomatic_complexity:
  warning: 20
  error: 100

file_length:
  warning: 800
  error: 3000

function_body_length:
  warning: 100
  error: 1200

line_length:
  warning: 200
  error: 250

type_body_length:
  warning: 600
  error: 2500
