import Foundation

/// Errors returned by the Bluesky API or generated by the client layer.
enum BlueskyAPIError: LocalizedError {
    /// The constructed URL or path was invalid.
    case invalidURL
    /// The API response could not be parsed or was unexpected.
    case invalidResponse
    /// Authentication failed (invalid credentials or expired token).
    /// The associated value contains the server-provided reason when available.
    case unauthorized(String?)
    /// No saved credentials were found for the requested account.
    case missingCredentials
    /// The server's SSL certificate did not match the pinned fingerprint.
    case sslPinFailure
    /// Email 2FA verification code is required to complete authentication.
    /// The associated value contains the server-provided delivery message.
    case authFactorTokenRequired(String?)
    /// The account has been deactivated (includes server message).
    case deactivated(String)
    /// A generic server-side error (includes server message).
    case server(String)
    /// The account's PDS is unreachable (DNS failure, connection refused, or 404).
    case pdsUnreachable(String)

    var errorDescription: String? {
        switch self {
        case .invalidURL:
            "The Bluesky endpoint URL is invalid."
        case .invalidResponse:
            "Bluesky returned an unexpected response."
        case let .unauthorized(message):
            if let message, !message.isEmpty {
                message
            } else {
                "Bluesky rejected the credentials. Check the handle and app password."
            }
        case let .authFactorTokenRequired(message):
            message.flatMap { $0.isEmpty ? nil : $0 } ?? "A verification code has been sent to your email."
        case .missingCredentials:
            "No saved app password was found for this account."
        case .sslPinFailure:
            "The server certificate does not match the pinned fingerprint."
        case let .deactivated(message):
            "This account has been deactivated: \(message)"
        case let .server(message):
            "Bluesky returned an error: \(message)"
        case let .pdsUnreachable(host):
            "PDS \(host) is not reachable. Check account configuration."
        }
    }
}

/// Represents a JSON error payload returned by the Bluesky API.
struct APIErrorPayload: Decodable {
    /// The error code or identifier.
    let error: String?
    /// A human-readable error message.
    let message: String?
}
