import Foundation

/// Errors returned by the Bluesky API or generated by the client layer.
enum BlueskyAPIError: LocalizedError {
    /// The constructed URL or path was invalid.
    case invalidURL
    /// The API response could not be parsed or was unexpected.
    case invalidResponse
    /// Authentication failed (invalid credentials or expired token).
    case unauthorized
    /// No saved credentials were found for the requested account.
    case missingCredentials
    /// The server's SSL certificate did not match the pinned fingerprint.
    case sslPinFailure
    /// The account has been deactivated (includes server message).
    case deactivated(String)
    /// A generic server-side error (includes server message).
    case server(String)

    var errorDescription: String? {
        switch self {
        case .invalidURL:
            "The Bluesky endpoint URL is invalid."
        case .invalidResponse:
            "Bluesky returned an unexpected response."
        case .unauthorized:
            "Bluesky rejected the credentials. Check the handle and app password."
        case .missingCredentials:
            "No saved app password was found for this account."
        case .sslPinFailure:
            "The server certificate does not match the pinned fingerprint."
        case let .deactivated(message):
            "This account has been deactivated: \(message)"
        case let .server(message):
            "Bluesky returned an error: \(message)"
        }
    }
}

/// Represents a JSON error payload returned by the Bluesky API.
struct APIErrorPayload: Decodable {
    /// The error code or identifier.
    let error: String?
    /// A human-readable error message.
    let message: String?
}
